---
title: "Data and analysis supporting the prioritization of species for stock assessments in 2021 and 2023"
author: ''
date: ''
output:
  pdf_document:
    fig_caption: yes
    highlight: haddock
    includes:
      before_body: Titlepage.tex
      in_header: header.tex
    keep_tex: yes
    number_sections: yes
    template: Default_template_modified.tex
    toc: yes
    toc_depth: 4
  html_document:
    toc: yes
  word_document:
    toc: yes
    toc_depth: '4'
documentclass: article
fontsize: 12pt
geometry: margin=1in
link-citations: yes
#csl: CJFAS.csl
#bibliography: Bib_July09.bib
#output:
#  uswebr::html_uswds
#documentclass: book
#fontsize: 11pt
#output:
#  pdf_document:   
#    keep_tex: yes
#header-includes:
#   - \RequirePackage{accsupp}
#   - \RequirePackage{pdfcomment}
#   - \newcommand{\AccTool}[2]{\BeginAccSupp{method=pdfstringdef,unicode,Alt={{#1}}}\pdftooltip{{#2}}{{#1}}\EndAccSupp{}}
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.pos = '!ht')
options(xtable.comment = FALSE)
library(xtable)
#devtools::install_github("rstudio/gt")
#library(gt)
source('./rcode/preamble.R')
```

\setlength{\parskip}{5mm plus1mm minus1mm}
\pagebreak


\setcounter{page}{1}
<!---
\renewcommand{\thefigure}{\alph{figure}}
\renewcommand{\thetable}{\alph{table}}
-->

\pagenumbering{arabic}


```{r child = "1_intro.Rmd"}
```


```{r child = "2_factors.Rmd"}
```


```{r child = "3_additional_info.Rmd"}
```


