
# Introduction

This document provides analysis that is intended to provide the Pacific Fishery Management Council (Council) and advisory bodies guidance on species specific assessment prioritization by synthesizing information by commercial fisheries, recreational fisheries, stock status, and other attributed defined as "Factors".  The work presented here follows the the general framework advanced in the 2015 National Marine Fisheries Service Technical Memorandum, ["Prioritizing Fish Stock Assessments"](https://www.st.nmfs.noaa.gov/Assets/stock/documents/PrioritizingFishStockAssessments_FinalWeb.pdf).  

This process was envisioned as a way of synthesizing a broad range of relevant information in a manner that can, over time, provide improved guidance, primarily on which species should be considered for benchmark (i.e., full) assessments, or subsequent stock assessment updates. The ranking process provides a useful tool for focusing discussion on species where a new assessment may have the greatest impact, but it is not a replacement for the judgment of the Council and advisory bodies. An important consideration for selecting any species for assessment is whether the (potentially) available data (e.g., trend and length- and age-composition data) are adequate to conduct the desired level of assessment. This aspect of prioritization is not scored in the way other factors are, and so must be considered independently, at this time.  In that regard, the process is likely to help identify important data gaps and/or situations where a data-moderate approach should be undertaken with whatever data are available.

The scoring and weighting of Factors in the associated **Excel workbook** remains a work in progress, particularly as we consider its ability, as currently configured, to provide useful insight into priorities in subsequent cycles, as requested by the Council. There may be important considerations that are not encompassed by any of the existing factors, or the methods by which Factor Scores are derived or weighted may be identified as needing improvement.  As consideration of priorities for `r ass.yr` are considered this spring it will be important to identify any parts of the scoring that could be improved.  As aspects of management change, this framework should adapt to reflect the manner in which those changes affect prioritization.  

The **Excel workbook** that accompanies this document begins with an Overview tab, followed by a Summary tab in which the Factor Scores are assembled and multiplied by the base-case weights, resulting in a total score and ranking.  Those are followed by a tab for each Factor, which documents the Factor scores and ranks for each species, and a Summary scoring worksheet. The following text provides a description of the content and issues associated with each tab, along with the source of data and information used in scoring each Factor.


# Description of Factors

## Factor Summary

The total scoring combines the scores by species from each factor using pre-defined weights for each factor. The total scoring by species is calculated as:
  
\begin{centering}
$\text{F}_s = w_c*c_{s} + w_r*r_{s}+w_t*t_{s}+w_d*d_{s}+w_o*o_{s}+w_b*b_s+w_h*h_s+w_e*e_s+w_n*n_s+w_a*a_s$
\end{centering}

where $w$ is the weight applied to each factor, $c$ is the commercial importance by species $s$, $r$ is the recreational importance by species $s$, $t$ is the tribal importance by species $s$, $d$ is he constituent demand or choke factor by species $s$, $o$ is rebuilding by species $s$, $b$ is relative stock status by species $s$, $h$ is harvest by species $s$, $e$ is ecosystem importance by species $s$, $n$ is new information available by species $s$, and $a$ is the assessment frequency by species $s$.The weights for each factor are shown in Table \ref{tab:weights}.

```{r, results = 'asis'}
library(xtable) #; library(kableExtra)
weight = matrix(NA, 10, 4)

colnames(weight) = c('Factor',
                     'Notation',
                     'Weight Notation',
                     'Weight')

weight[1,] = c("Commercial Importance", "$c$","$w_c$", 0.21)
weight[2,] = c("Recrational Importance", "$r$", "$w_r$", 0.09)
weight[3,] = c("Tribal Importance", "$t$","$w_t$", 0.05)
weight[4,] = c("Constituant Demand/Choke Species", "$d$","$w_d$", 0.11)
weight[5,] = c("Rebuild", "$o$", "$w_o$", '0.10')
weight[6,] = c("Relative Stock Status", "$b$", "$w_b$", 0.08)
weight[7,] = c("Harvest Status", "$h$", "$w_h$", 0.08)
weight[8,] = c("Ecosystem Importance", "$e$", "$w_e$", 0.05)
weight[9,] = c("New Information Available", "$n$", "$w_n$", 0.05)
weight[10,] = c("Assessment Frequency", "$a$", "$w_a$", 0.18)

weight.table = xtable(weight, 
                      caption = c('Weights used for each factor in the calculation of total factor score by species'),
                      label = 'tab:weights',
                      digits = c(0,0,0,0,2))

# Add alignment  
align(weight.table) = c('l',
                        '>{\\raggedright}p{3in}',
                        '>{\\centering}p{1in}',
                        '>{\\centering}p{1in}',
                        '>{\\centering}p{1in}')  

print(weight.table, 
      include.rownames=FALSE, 
      caption.placement='top',
      sanitize.text.function = function(x){x})

```

\FloatBarrier
