
## Commercial Importance

The commercial importance score is based on the coastwide ex-vessel revenue generated by commercial landings of groundfish during the period `r start_yr` - `r end_yr`. The revenue amounts generally have a very large range across groundfish species.  Consequently, a transformation is used to compress the distribution and reduce the differences between species.  

A logarithmic transformation is used to compress the distribution with the values standardized to a maximum value of 10:

\begin{equation}
  \text{Initial Score}_{s} = log(\text{revenue}_s + 1) + \text{recently assessed penalty}_s
\end{equation}

where revenue is the total commercial ex-vessel revenue across the summarizing years for each species $s$ and the $\text{recently assessed penalty}_s$ is -2 for species that were assesed in the most recent assessment cycle or 0 for all other species. The scores are then standardized to range between 0 and 10. Ex-vessel revenue amounts were obtained from the Pacific Fisheries Information Network (PacFIN) and were summed across the five-year period of `r start_yr`-`r end_yr`. Only commercial revenue is accounted for under this factor with any tribal landings are accounted for by the Tribal Importance Factor. 