
## Tribal Importance

West Coast groundfish species are highly important to coastal Tribes. The Subsistence category identified in the NMFS guidance document [@methot_prioritizing_2015] was expanded to include the value of Tribal fishing for both commercial sale and subsistence and ceremonial uses. The Tribal Importance Factor is calculated as:
  
\begin{equation}
\text{Initial Score}_{s} = \alpha * log(\text{revenue}_{s} + 1) + \beta_s + \text{recently assessed penalty}_s   
\end{equation}
  
where $\text{revenue}_s$ is the revenue based on ex-vessel prices by species $s$, $\alpha$ is the initial factor score set equal to 7.0, $\beta_s$ is the tribal importance score by species $s$ (Table \ref{tab:tribal-score}), and the recently assessed penalty that is -2 for species that were assesed in the most recent assessment cycle or 0 for all other species. The scores are then standardized to range between 0 and 10. The tribal landings ex-revenue was pulled from PacFIN with the total revenue summed across the five-year period of `r start_yr`-`r end_yr`. 

The tribal importance scores range from 0 to 3.0 and represent the relative value of groundfish species to tribal harvesters (Table \ref{tab:tribal-score}). These species scores were refined through consultation with Tribal representatives with the values initially developed in 2016 and updated in 2024. Continued comments/input from the tribal community regarding tribal scores will ensure that the scoring reflect the current prioritization of the tribal sector. 
  
```{r, results = 'asis'}

tab = read.csv("tables/tribal_score.csv", header = TRUE) 
col_names = c("Species", "Score")
  
t = table_format(tab, 
             caption = c('Tribal score by species. The tribal score is colored reflecting low to high scores ranging between blue to green, respectively.'),
             label = 'tribal-score',
             col_names = col_names,
             digits = 2,
             align = c('l','c'),
             custom_width = TRUE,
             col_to_adjust = 1:2,
             width = c("8cm", "1cm"))


t %>%
    kableExtra::column_spec(2, 
        color = "white", 
        bold = TRUE,
        background = kableExtra::spec_color(x = tab[,"Score"], 
        alpha = 1, begin = 0.2, end = 0.8, option = 'D', direction = 1))

#t %>%
#    kableExtra::column_spec(2, 
#        color = "black", 
#        bold = TRUE,
#        background = kableExtra::spec_color(x = tab[,"Score"], 
#        alpha = 1, begin = 0.6, end = 1, option = 'D', direction = 1))

#t %>%
#    kableExtra::column_spec(2, 
#        color = kableExtra::spec_color(x = tab[,"Score"], 
#        begin = 0.3, end = 1, option = 'D', direction = 1),
#        bold = TRUE)
  
```

