\newpage

## Recreational Importance

Recreational landings lack a measure of value that is equivalent to commercial ex-vessel revenue. In the absence of an equivalent metric, these rankings rely on state-specific species-importance score to adjust the recreational catches based on the importance of the species. The species-specific scores are used to calculate "pseudo" revenues by state based on total recreational catches over a range of years in each state by a set of state-specific importance scores, which serve the same function as prices. The coastwide pseudo revenue by species is calculated as:

\begin{equation}
\text{Pseudo Revenue}_{s} = \sum_{a=1}^{A} \text{catch}_{s,a}*\text{importance score}_{s,a}  
\end{equation}

where catch is the recreational catch by species $s$ and state $a$ and importance score by species $s$ and state $a$. The catch data are pulled from the WCGOP GEMM report with catches between `r start_yr`-`r end_yr` summed. The recreational importance score by species and state are shown in Table \ref{tab:recr-import}. These weights were initially developed in cooperation with the state recreational representatives to the Groundfish Management Team and reviewed by the Groundfish Advisory Panel in 2016 and updated in 2024 based on input from state representatives to reflect current recreational fishery conditions.

The overall factor for recreational importance is then calculated as:

\begin{centering}

$\text{Initial Score}_s = log(\text{pseudo revenue}_s + 1) + \text{recently assessed penalty}_s$  

\end{centering}

<!--
\begin{equation}
r_{s} = \frac{10}{\text{max}(\text{pseudo}_{s})} \text{pseudo}_{s}^{0.18} 
\end{equation}
-->

where the recently assessed penalty is -2 for species that were assesed in the most recent assessment cycle or 0 for all other species. 

The transformed scores are then standardized to range between 0 and 10:

\begin{equation}
  r_{s} = \frac{10 * log(\text{Initial Score}_s + 1)}{\text{max}(log(\text{Initial Score}_s + 1))}
\end{equation}


Continued comments and input from the recreational fishing community or state agencies regarding relative value of species among recreational fishery participants of each state will allow these weights to reflect the current priority of the recreational sector.

  
```{r, results = 'asis', fig.pos = 'H'}
tab = read.csv("tables/recr_importance.csv", header = TRUE) 
col_names = c("Species", "California", "Oregon", "Washington")
tab[is.na(tab)] = 0

t = table_format(tab, 
             caption = c('Recreational species importance by state based on the relative species desirability to recreational anglers.'),
             label = 'recr-import',
             align = c('l','r','r','r','r'),
             col_names = col_names,
             digits = c(0,2,2,2,2),
             custom_width = TRUE,
             col_to_adjust = 1:4,
             width = c("6cm", rep("2cm", 3)))  

t %>%
    kableExtra::column_spec(2, 
        color = "white", 
        bold = TRUE,
        background = kableExtra::spec_color(x = tab[, 2], 
        alpha = 1, begin = 0.2, end = 0.8, option = 'D', direction = 1)) %>%
    kableExtra::column_spec(3, 
        color = "white", 
        bold = TRUE,
        background = kableExtra::spec_color(x = tab[, 3], 
        alpha = 1, begin = 0.2, end = 0.8, option = 'D', direction = 1)) %>%
    kableExtra::column_spec(4, 
        color = "white", 
        bold = TRUE,
        background = kableExtra::spec_color(x = tab[, 4], 
        alpha = 1, begin = 0.2, end = 0.8, option = 'D', direction = 1))
  
```