## Constituent Demand

The constituent demand factor includes aspects of species importance that may not be adequately captured by coastwide measures of commercial and recreational importance. Additionally, this factor also measures the potential for species to be choke species within the fishery given future Annual Catch Limits relative to current average catch. 

The first element examines commercial importance by state and trawl or non-trawl ex-vessel revenues comparing then to the coastwide totals in order to identify species that are considerably more important to a segment of the commercial fishery compared to their coastwide importance. The ex-vessel revenue is summed across recent years by state and gear grouping. The summed ex-vessel revenue by species is then ranked within each state and gear group with and standardized to range between 0 and 1. Any species that has a state-specific standardized score greater than 0.10 compared to the coastwide score is assigned a +1 for each state and any species that is equally important to both the trawl and non-trawl gear types is assigned a +1. The state-specific and gear-specific adjustments are then summed to determine the commercial importance modifier.     

The second element examines the recreational catches by state compared to the coastwide totals. Similar to commercial ex-vessel revenue, the catches are ranked and standardized by each state and compared to the ranked and standardized coastwide values. Any species that has a state-specific standardized score greater than 0.10 compared to the coastwide value is assigned a +1 for each state. The state-specific adjustments are then summed to determine the recreational importance modifier. 

The third element accounts for species that currently are or could be choke stocks based on current average catches compared to expected future ACLs. Future ACLs may be constraining due to stock status, small unfished population sizes, or due to decreasing ACLs given increases in time-varying uncertainty for species with older assessments. Species are assigned a score ranging between 0 to 5 depending upon the projected ACL attainment given current average catches (Table \ref{tab:choke}). The current average catch from the fishing mortality factor was used to compare to `ass_yr` anticipated ACLs.


```{r, results = 'asis', fig.pos = 'H'}

mort = matrix(NA, 6, 2)
col_names = c("Choke Score", "Projected Future ACL Attainment")

mort[1,]  = c(0, "Current Average Catch $\\le$ 0.70*ACL")
mort[2,]  = c(1, "0.70*ACL $<$ Current Average Catch $\\le$ 0.80*ACL")
mort[3,]  = c(2, "0.80*ACL $<$ Current Average Catch $\\le$ 0.90*ACL")
mort[4,]  = c(3, "0.90*ACL $<$ Current Average Catch $\\le$ ACL")
mort[5,]  = c(4, "ACL $<$ Current Average Catch $\\le$ 1.1*ACL")
mort[6,]  = c(5, "1.25*ACL $<$ Current Average Catch")

table_format(mort, 
             caption = c('Choke scores applied based the percent of the projected ACL attainment given current average catches by species.'),
             label = 'choke',
             align = 'l',
             escape = FALSE,
             col_names = col_names,             
             custom_width = TRUE,
             col_to_adjust = 1:2,
             width = c("3cm","10cm"))

```


The overall score for constituent demand score is calculated as:

\begin{centering}

$d_s = \text{Choke Score}_s + \text{Commercial Importance Modifier}_s + \text{Recreational Importance Modifier}_s $

\end{centering}

