
## Rebuilding Status

This factor provides another means of emphasizing the importance of rebuilding stocks, whose harvest amounts are generally highly restricted. The highest possible score would be assigned to species that are being managed under rebuilding plans and the estimated spawning output is continuing to decline. The next highest score accounts for species that are currently managed under a rebuilding plan and that the projected time for rebuilding is within two assessment cycles (i.e., four years). Species with longer anticipated rebuilding times receive lower scores than those with shorter ones. Table \ref{tab:rebuild} shows how the scores are assigned for this factor according to rebuilding status of the species.

```{r, results = 'asis'}
score = matrix(NA, 5, 2)
col_names = c("Score", "Rebuilding Status")

score[1,] = c(0, "Not in rebuilding")
score[2,] = c(4, "Projected to rebuild in over 20 years")
score[3,] = c(6, "Projected to rebuild within 20 years")
score[4,] = c(9, "Projected to rebuild within 4 years")
score[5,] = c(10, "In rebuilding with declining biomass trajectory")


table_format(score, 
             caption = c('Factor scores applied based on rebuilding status.'),
             label = 'rebuild',
             align = 'l',
             col_names = col_names,             
             custom_width = TRUE,
             col_to_adjust = 1:2,
             width = c("1cm","8cm"))

```

### Reconsidering the use of Rebuilding Status Measures

The inclusion of rebuilding status within the groundfish assessment prioritization process is subject to similar concerns as to the inclusion of stock status. Feedback from PFMC advisory bodies is welcome on whether and how this factor should be revised for future groundfish assessment prioritizations.  
