## Relevant New Types of Information Available

As new types or sources of useful information or methods become available for a species, the potential value of conducting a new assessment for it increases. The scoring of the new information factor incorporates various types of new information that account for survey indices, survey compositions, new research, assumptions about steepness for rockfish species, and the ability to address known assessment issues. 

The first two types of information considered in this factor are for new or extended survey time series of relative abundance information and for additional composition data, such as length and age (or otoliths available) data. At this time the survey considered are the Northwest Fisheries Science Center (NWFSC) West Coast Groundfish Bottom Trawl (WCGBT) and Hook and Line (HKL) surveys since they publicly available and accessible. In the future, this factor will work to include additional survey data sources if they are available. The metrics for scoring based upon the quantity of available survey data is shown in Table \ref{tab:survey-data}.  

```{r, results = 'asis', fig.pos = 'H'}

mort = matrix(NA, 8, 2)
col_names = c("Abundance and Composition", "Data Quantity")

mort[1,]  = c(3, "Species has not yet been assessed and there are $>$ positive tows by year on average.")
mort[2,]  = c(2, "Additionaly years in the time series since last assessment is $>$ 10 years and $>$ positive tows by year on average.")
mort[3,]  = c(1, "Additionaly years in the time series since last assessment is $>$ 5 and $\\le$ 10 years and $>$ positive tows by year on average.")
mort[4,]  = c(0, "Time series not available or there are $<$ positive tows by year on average.")
mort[5,]  = c(3, "Number of available lengths, ages, and otoliths $>$ 20,000 since last assessment.")
mort[6,]  = c(2, "Number of available lengths, ages, and otoliths $>$ 10,000 and $\\le$ 20,000 since last assessment.")
mort[7,]  = c(1, "Number of available lengths, ages, and otoliths $>$ 5,000 and $\\le$ 10,000 since last assessment.")
mort[8,]  = c(0, "Number of available lengths, ages, and otoliths $\\le$ 5,000 since last assessment.")

table_format(mort, 
             caption = c('Scoring based on the available survey time series of relative abundance and survey composition data.'),
             label = 'survey-data',
             align = 'l',
             escape = FALSE,
             col_names = col_names,             
             custom_width = TRUE,
             col_to_adjust = 1:2,
             width = c("3cm","10cm"))

```

The new information factor also aims to account for new groundfish research on species biology, dynamics, genetics, or any other research that could be used to inform a new assessment. The scoring for new research is somewhat subjective but generally any new research that would better inform parameterization (e.g., maturity, fecundity) or how a species is managed (e.g., percentage of cryptic species within a region that could inform assessment categorization) are assigned a score of +1 and any research that would dramatically change how a species is modeled (e.g., genetic differences to inform stock definition) are assigned a +4. Finally, the assumptions around rockfish steepness has evolved over time where historically older assessments assumed a less productive stock prior compared to the current assumptions around rockfish productivity. Any rockfish assessment where the steepness was fixed at a value less than 0.60 for reasons not specific to that assessment (e.g., Pacific ocean perch assumed a value of 0.50 based on guidance from the Groundfish Subcommittee to the Scientific and Statistical Committee) a value of +1 is applied. The overall score for new research is then based on the summed new research type by species. 

Finally, points are assigned where issues or problems identified during the review of prior assessments can now be addressed through the inclusion of newly available data or methods. These types of new information are considered significant improvements to the assessment and are assigned a score of +5.  The

The overall scoring for this factor is calculated as:

$$
n_s = \text{Time Series of Relative Abundance}_s + \text{Composition Data}_s + \text{New Research}_s +  \text{Issues}_s
$$
