## Future Limiting Harvest Specifications{#future-spex-sec}

The assessment prioritization for the first time in 2020 explored the potential for future catch to be constrained relative to future OFLs and ABCs.  The Council adopted a time-varying $\sigma$ resulting in increased uncertainty and greater reduction between the OFL and the ABC as the time from last assessment increases.  A similar analysis was also conducted this year.  

The potential impacts of limiting future harvest specification relative to recent average catches is not incorporated as its own Factor but rather as a modifier to adjust the Constituent Demand Factor scoring.  The modifier that ranges from -2.0 to +4.0 is calculated based on the potential future percent attainments.  The ratio of the average mortality between `r start_yr`-`r end_yr` to the future Annual Catch Limit (ACL) in `r end_yr + 4` (i.e., only draft harvest specifications were available at the time of the analysis) is calculated to determine the potential future attainment percentage.  A Factor score is then calculated using the same methodology as applied to calculate Fishing Mortality Factor scores (see Table \ref{tab:mort}). The modifier score is then determined based on the Factor score, except in the case for stocks undergoing rebuilding which are given a default value of +4.0 (Table \ref{tab:future-spex}). 

```{r, results = 'asis', fig.pos = 'h!'}
mort = matrix(NA, 7, 2)
col_names = c("Factor Score", "Modifier")

mort[1,]  = c(10, 4)
mort[2,]  = c(9, 3)
mort[3,]  = c(8, 2)
mort[4,]  = c(7, 1)
mort[5,]  = c("5 - 6", 0)
mort[6,]  = c("2 - 4", -1)
mort[7,]  = c(1, 2)


table_format(mort, 
             caption = c('Modifier values based the future specification Factor score. Factor score values are based on the percent attainment between recent average catches and future ACL values.  '),
             label = 'future-spex',
             align = 'l',
             escape = FALSE,
             col_names = col_names,             
             custom_width = TRUE,
             col_to_adjust = 1:2,
             width = c("1cm","2cm"))
                          

```