
## Stock Assessment History

All stock assessments conducted between 2003 - `r end_yr` are shown in Table \ref{tab:ass-hist}. Table \ref{tab:ass-hist} provides information on the type of assessment (e.g., F = full, U = update) conducted for each year assessed, the area stratifications, and the most recent estimate of stock status. 

```{r, results='asis'}
library(dplyr)

ass = read.csv('tables/assessment_history.csv', header = T)
col_names = c('Species', seq(2003, 2021, 2), 'Status')
#col_names = c('Species', '2003', '2005','2007','2009','2011','2013','2015','2017','2019',#
#	'2021', 'Status')
ass[is.na(ass[,ncol(ass)]), ncol(ass)] = "---"

t = table_format(ass, 
             caption = c('History of assessment since 2003 for West Coast groundfish stocks where F = full assessment, U = update assessment, DM = data moderate assessment, and DL = data limited (category 3). Only stocks that have been fully assessed (category 1 or 2) at least once since 2003 are shown in this table.  A * indicates an assessment that was rejected by the SSC.'),
             label = 'ass-hist',
             landscape = TRUE,
             escape = FALSE,
             font = 10,
             align = c('l', 'l', rep('c', ncol(ass))),
             col_names = col_names,
             custom_width = TRUE,
             col_to_adjust = 1,
             width = "6cm")

t %>%
	kableExtra::row_spec(1:nrow(ass), hline_after = TRUE)

```

```{r, results='asis'}

summary = read.csv('tables/assessment_summary.csv', header = T)
col_names = c('', seq(2003, 2021, 2), 'Total', 'Average 2007-2021')
summary[is.na(summary)] = ""


table_format(summary, 
             caption = c('Summary ot the type of assessments conduect each year, the number of modeled areas, number of species assessed, and the difference by year.'),
             label = 'summary',
             landscape = TRUE,
             escape = FALSE,
             font = 10,
             align = c('l', 'l', rep('c', ncol(summary))),
             col_names = col_names,
             custom_width = TRUE,
             col_to_adjust = 1,
             width = "6cm")



```