
pacfin_with_nominal_species_code = c(
	"ARR1", "ARRA", "ART1", "ARTH", "BANK", "BCAC", "BCC1", "BGL1", "BLCK", "BLGL", "BLK1", "BLU1", "BLUR", "BNK1", "BRW1", "BRWN", "BSK1", "BSKT", "BYEL", "BYL1", "CBZ1",
	"CBZN", "CHN1", "CHNA", "CLP1", "CLPR", "CNR1", "CNRY", "COP1", "COPP", "CWC1", "CWCD", "DBR1", "DBRK", "DOVR", "DSRK", "DVR1", "EGL1", "EGLS", "FLAG", "FLG1", "FSOL",
	"GPH1", "GPHR", "GRAS", "GRS1", "GSP1", "GSPT", "GSR1", "GSRK", "HNY1", "HNYC", "KGL1", "KLP1", "KLPG", "KLPR", "LCD1", "LCOD", "LSKT", "LSP1", "LSPN", "OLV1", "OLVE",
	"PCOD", "PDAB", "PDB1", "POP" , "POP2", "PTR1", "PTRL", "QLB1", "QLBK", "RDB1", "RDBD", "REX" , "REX1", "REY1", "REYE", "RSL1", "RSOL", "SABL", "SCOR", "SCR1", "SFL1",
	"SHRP", "SNOS", "SNS1", "SPK1", "SPKL", "SQR1", "SQRS", "SRK1", "SRKR", "SSO1", "SSOL", "SSP1", "SSPN", "STAR", "STR1", "STRY", "TRE1", "TREE", "UPOP", "VRM1", "VRML",
	"WDOW", "WDW1", "YEY1", "YEYE", "YTR1", "YTRK")

pacfin_species_code = c(
    "ARRA", "ARTH", "BANK", "BCAC", "BLCK", "BLGL", "BLUR", "BRWN", "BSKT", "BYEL", "CBZN", "CHNA", "CLPR", "CNRY", "COPP", "CWCD", "DBRK", "DOVR", "DSRK", "EGLS", "FLAG",
    "FSOL", "GPHR", "GRAS", "GSPT", "GSRK", "HNYC", "KLPG", "KLPR", "LCOD", "LSKT", "LSPN", "OLVE", "PCOD", "PDAB", "POP" , "PTRL", "QLBK", "RDBD", "REX" , "REYE", "RSOL",
    "SABL", "SCOR", "SHRP", "SNOS", "SPKL", "SQRS", "SRKR", "SSOL", "SSPN", "STAR", "STRY", "TREE", "VRML", "WDOW", "YEYE", "YTRK")

pacfin_species_code_key = c(
	'ARRA',	'aurora rockfish',
	'ARTH',	'arrowtooth flounder',
	'BANK',	'bank rockfish',
	'BCAC',	'bocaccio',
	'BLCK',	'black rockfish',
	'BLGL',	'blackgill rockfish',
	'BLUR',	'blue rockfish',
	'BRWN',	'brown rockfish',
	'BSKT',	'big skate',
	'BYEL',	'black and yellow rockfish',
	'CBZN',	'cabezon',
	'CHNA',	'china rockfish',
	'CLPR',	'chilipepper rockfish',
	'CNRY',	'canary rockfish',
	'COPP',	'copper rockfish',
	'CWCD',	'cowcod',
	'DBRK',	'darkblotched rockfish',
	'DOVR',	'dover sole',
	'DSRK',	'pacific spiny dogfish',
	'EGLS',	'english sole',
	'FLAG',	'flag rockfish',
	'FSOL',	'flathead sole',
	'GPHR',	'gopher rockfish',
	'GRAS',	'grass rockfish',
	'GSPT',	'greenspotted rockfish',
	'GSRK',	'greenstriped rockfish',
	'HNYC',	'honeycomb rockfish',
	'KLPG',	'kelp greenling',
	'KLPR',	'kelp rockfish',
	'LCOD',	'lingcod',
	'LSKT',	'longnose skate',
	'LSPN',	'longspine thornyhead',
	'OLVE',	'olive rockfish',
	'PCOD',	'pacific cod',
	'PDAB',	'pacific sanddab',
	'POP' ,	'pacific ocean perch',
	'PTRL',	'petrale sole',
	'QLBK',	'quillback rockfish',
	'RDBD',	'redbanded rockfish',
	'REX' ,	'rex sole',
	'REYE',	'rougheye rockfish',
	'RSOL',	'rock sole',
	'SABL',	'sablefish',
	'SCOR',	'california scorpionfish',
	'SHRP',	'sharpchin rockfish',
	'SNOS',	'splitnose rockfish',
	'SPKL',	'speckled rockfish',
	'SQRS',	'squarespot rockfish',
	'SRKR',	'shortraker rockfish',
	'SSOL',	'sand sole',
	'SSPN',	'shortspine thornyhead', 
	'STAR',	'starry rockfish',
	'STRY',	'starry flounder',
	'TREE',	'treefish rockfish',
	'VRML',	'vermilion rockfish',
	'WDOW',	'widow rockfish',
	'YEYE',	'yelloweye rockfish',
	'YTRK',	'yellowtail rockfish')
